### ISSUE TITLE
just crashes

### ISSUE THREAD

**Issue by treakiandroid** [yeriomin/YalpStore#21]
```
01-03 02:04:44.290 32378 22452 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.github.yeriomin.yalpstore cmp=com.github.yeriomin.yalpstore/.UpdatableAppsActivity} from uid 10069 on display 0                                                             01-03 02:04:44.410 32378  8109 I ActivityManager: Start proc 31127:com.github.yeriomin.yalpstore/u0a316 for activity com.github.yeriomin.yalpstore/.UpdatableAppsActivity                          01-03 02:04:54.339 31127 31154 E AndroidRuntime: Process: com.github.yeriomin.yalpstore, PID: 31127                               01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.Version.normalize(Version.java:12) 01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.Version.<init>(Version.java:8)     01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.App.setVersionName(App.java:66)    01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.App.setPackageInfo(App.java:48)    01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.App.<init>(App.java:35)            01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.AppListActivity.getInstalledApps(AppListActivity.java:126)                                                01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask.doInBackground(UpdatableAppsActivity.java:50)                    01-03 02:04:54.339 31127 31154 E AndroidRuntime:        at com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask.doInBackground(UpdatableAppsActivity.java:42)                    01-03 02:04:54.343 32378  1159 W ActivityManager:   Force finishing activity com.github.yeriomin.yalpstore/.UpdatableAppsActivity 01-03 02:04:59.357 32378 32393 I ActivityManager: Process com.github.yeriomin.yalpstore (pid 31127) has died                      01-03 02:05:28.551 32378  1160 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.github.yeriomin.yalpstore cmp=com.github.yeriomin.yalpstore/.UpdatableAppsActivity} from uid 10069 on display 0                                                             01-03 02:05:28.644 32378  2239 I ActivityManager: Start proc 466:com.github.yeriomin.yalpstore/u0a316 for activity com.github.yeriomin.yalpstore/.UpdatableAppsActivity                            01-03 02:05:28.826   466   466 W System  : ClassLoader referenced unknown path: /data/app/com.github.yeriomin.yalpstore-1/lib/arm 01-03 02:05:37.503   466   508 E AndroidRuntime: Process: com.github.yeriomin.yalpstore, PID: 466                                 01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.Version.normalize(Version.java:12) 01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.Version.<init>(Version.java:8)     01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.App.setVersionName(App.java:66)    01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.App.setPackageInfo(App.java:48)    01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.model.App.<init>(App.java:35)            01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.AppListActivity.getInstalledApps(AppListActivity.java:126)                                                01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask.doInBackground(UpdatableAppsActivity.java:50)                    01-03 02:05:37.503   466   508 E AndroidRuntime:        at com.github.yeriomin.yalpstore.UpdatableAppsActivity$1UpdatableAppsTask.doInBackground(UpdatableAppsActivity.java:42)                    01-03 02:05:37.507 32378  2293 W ActivityManager:   Force finishing activity com.github.yeriomin.yalpstore/.UpdatableAppsActivity 01-03 02:05:38.659   466   466 E WindowManager: android.view.WindowLeaked: Activity com.github.yeriomin.yalpstore.UpdatableAppsActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{b91c183 V.E...... R......D 0,0-684,322} that was originally added here                                                   01-03 02:05:38.659   466   466 E WindowManager:         at com.github.yeriomin.yalpstore.GoogleApiAsyncTask.onPreExecute(GoogleApiAsyncTask.java:46)                                               01-03 02:05:38.659   466   466 E WindowManager:         at com.github.yeriomin.yalpstore.UpdatableAppsActivity.loadApps(UpdatableAppsActivity.java:107)                                            01-03 02:05:38.659   466   466 E WindowManager:         at com.github.yeriomin.yalpstore.AppListActivity.onCreate(AppListActivity.java:60)                                                         01-03 02:05:38.659   466   466 E WindowManager:         at com.github.yeriomin.yalpstore.UpdatableAppsActivity.onCreate(UpdatableAppsActivity.java:18)                                             01-03 02:05:39.386 32378  9219 I ActivityManager: Process com.github.yeriomin.yalpstore (pid 466) has died                        01-03 02:05:41.835 32378  4915 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.github.yeriomin.yalpstore cmp=com.github.yeriomin.yalpstore/.UpdatableAppsActivity} from uid 10069 on display 0
```

**Comment by k3b** [comment]
is this a duplicate of #12 ?
