### ISSUE TITLE
Entering preferences screen causes a crash on Amazon TVs

### ISSUE THREAD

**Issue by yeriomin** [yeriomin/YalpStore#363]
### Expected behaviour
A list of configurable preferences should be shown.

### Actual behaviour
Yalp Store crashes, see stack trace below.

### Steps to reproduce
1. Tap "Settings" in the main menu

### Info about your device
Most Amazon TV devices: tank, sloane, montoya. Judging by the frequency of the bug reports, it is happening on every attempt to enter settings.

Here is the stack trace:

```
android.view.InflateException: "Binary XML file line #18: Error inflating class <unknown>"
	at android.view.LayoutInflater.createView(LayoutInflater.java:637)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:686)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at android.preference.Preference.onCreateView(Preference.java:511)
	at android.preference.Preference.getView(Preference.java:488)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
	at android.widget.AbsListView.obtainView(AbsListView.java:2367)
	at android.widget.ListView.makeAndAddView(ListView.java:1880)
	at android.widget.ListView.fillDown(ListView.java:709)
	at android.widget.ListView.fillFromTop(ListView.java:770)
	at android.widget.ListView.layoutChildren(ListView.java:1689)
	at android.widget.AbsListView.onLayout(AbsListView.java:2171)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1090)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:781)
	at android.view.Choreographer.doCallbacks(Choreographer.java:592)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:767)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5483)
	at java.lang.reflect.Method.invoke(Method.java:-2)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.reflect.InvocationTargetException: "null"
	at java.lang.reflect.Constructor.newInstance(Constructor.java:-2)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:611)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:686)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at android.preference.Preference.onCreateView(Preference.java:511)
	at android.preference.Preference.getView(Preference.java:488)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
	at android.widget.AbsListView.obtainView(AbsListView.java:2367)
	at android.widget.ListView.makeAndAddView(ListView.java:1880)
	at android.widget.ListView.fillDown(ListView.java:709)
	at android.widget.ListView.fillFromTop(ListView.java:770)
	at android.widget.ListView.layoutChildren(ListView.java:1689)
	at android.widget.AbsListView.onLayout(AbsListView.java:2171)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1090)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:781)
	at android.view.Choreographer.doCallbacks(Choreographer.java:592)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:767)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5483)
	at java.lang.reflect.Method.invoke(Method.java:-2)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.RuntimeException: "Failed to resolve attribute at index 5"
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:427)
	at android.widget.TextView.<init>(TextView.java:1009)
	at android.widget.TextView.<init>(TextView.java:650)
	at android.widget.TextView.<init>(TextView.java:646)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:-2)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:611)
	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:686)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:745)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:486)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
	at android.preference.Preference.onCreateView(Preference.java:511)
	at android.preference.Preference.getView(Preference.java:488)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:246)
	at android.widget.AbsListView.obtainView(AbsListView.java:2367)
	at android.widget.ListView.makeAndAddView(ListView.java:1880)
	at android.widget.ListView.fillDown(ListView.java:709)
	at android.widget.ListView.fillFromTop(ListView.java:770)
	at android.widget.ListView.layoutChildren(ListView.java:1689)
	at android.widget.AbsListView.onLayout(AbsListView.java:2171)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1692)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1468)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1703)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1557)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1466)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16076)
	at android.view.ViewGroup.layout(ViewGroup.java:5051)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2122)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1090)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5988)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:781)
	at android.view.Choreographer.doCallbacks(Choreographer.java:592)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:767)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5483)
	at java.lang.reflect.Method.invoke(Method.java:-2)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:984)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

This exception is a styling error, but Yalp Store does not use any non-standard styling (almost no styling at all). The stack trace does not even mention any class belonging to the Yalp Store project. If I had to bet, I would say that the problem is with https://github.com/yeriomin/YalpStore/blob/master/app/src/main/java/com/github/yeriomin/yalpstore/MultiSelectListPreference.java. But it is copied from android source code and I cannot be sure it causes this problem. 

I do not have any Amazon devices available and the information from bug reports is not sufficient to fix this bug. I would really appreciate any help from anyone who has an Amazon TV and has any experience with android development.

**Comment by sherpya** [comment]
I'm trying to debug the same problem, and it's not related with the layout of MultiSelectListPreference since I've got the same crash with the code disabled, but since it complains about typed array it may be somehow involved.

**Comment by sherpya** [comment]
It's a TextView inside `"Updates"` `PreferenceCategory`, TextView_textStyle or TextView_typeface (aosp api 22 sources are a bit different)

`return mResources.loadColorStateList(value, value.resourceId);`
`index = 5`
`value = TypedValue{t=0x2/d=0x1010435 a=-1}` -> resourcesId is 0

**Comment by sherpya** [comment]
I think your theme misses some stylable attribute for `TextView`,
adding
`android:theme="@android:style/Theme.Black"` to the activity tag in the manifest makes the settings activity work

**Comment by sherpya** [comment]
PreferenceActivity on FireTV does not like no theme, I've tested forcing LIGHT, DARK and BLACK, but with NONE it crashes

**Comment by yeriomin** [comment]
> android:theme="@android:style/Theme.Black"

That would disable themes for all the other devices. Setting it programmatically on amazon tvs only is possible.

> I've tested forcing LIGHT, DARK and BLACK, but with NONE it crashes

Thanks a lot! Looks like creating a workaround for this is easy.

Could you check if the fix I've committed to master works?

**Comment by sherpya** [comment]
confirmed working on firetv stick 2nd gen (api 22)

**Comment by yeriomin** [comment]
@sherpya Thanks again.

**Comment by yeriomin** [comment]
@sherpya Could you look at #392, please? Looks exactly the same as this bug. Do the current versions of Yalp Store work properly on your Amazon device?
