### ISSUE TITLE
crash after downloading apk

### ISSUE THREAD

**Issue by twouters** [yeriomin/YalpStore#37]
```build.board: MSM8974
build.bootloader: unknown
build.brand: oneplus
build.cpu_abi: armeabi-v7a
build.cpu_abi2: armeabi
build.device: A0001
build.display: bacon-userdebug 7.1.1 NMF26V ee768d1a56 test-keys
build.fingerprint: oneplus/bacon/A0001:6.0.1/MHC19Q/ZNH2KAS1KN:user/release-keys
build.hardware: bacon
build.host: lineageos
build.id: NMF26V
build.manufacturer: OnePlus
build.model: A0001
build.product: bacon
build.radio: unknown
build.serial: a266d6de
build.tags: test-keys
build.time: 1484656129000
build.type: user
build.user: twouters
version.codename: REL
version.incremental: ee768d1a56
version.release: 7.1.1
version.sdk_int: 25

01-18 23:56:11.236 E/AndroidRuntime(17956): Process: com.github.yeriomin.yalpstore, PID: 17956
01-18 23:56:11.236 E/AndroidRuntime(17956): java.lang.RuntimeException: Unable to start receiver com.github.yeriomin.yalpstore.DownloadBroadcastReceiver: java.lang.IllegalArgumentException: Failed to find configured root that contains /file:/storage/emulated/0/Download/de.ph1b.audiobook.150.apk
01-18 23:56:11.236 E/AndroidRuntime(17956): 	at com.github.yeriomin.yalpstore.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:631)
01-18 23:56:11.236 E/AndroidRuntime(17956): 	at com.github.yeriomin.yalpstore.FileProvider.getUriForFile(FileProvider.java:360)
01-18 23:56:11.236 E/AndroidRuntime(17956): 	at com.github.yeriomin.yalpstore.PlayStoreApiWrapper.getOpenApkIntent(PlayStoreApiWrapper.java:248)
01-18 23:56:11.236 E/AndroidRuntime(17956): 	at com.github.yeriomin.yalpstore.DownloadBroadcastReceiver.onReceive(DownloadBroadcastReceiver.java:35)
```

**Comment by yeriomin** [comment]
This seems to have been fixed in 0.4. I tagged it 2 days ago, but it isn't on f-droid yet.
Thanks for a well-written bug report.

**Comment by twouters** [comment]
Thanks, I'll test verify once it's available on f-droid.
Not sure if I smell some sarcasm in your reply though :-)

**Comment by yeriomin** [comment]
Just look at the other issues. Only one of them includes a logcat, and no build constants anywhere. I'm going to point users to your issue as an example ^^

**Comment by twouters** [comment]
Works fine in 0.4 as expected.
