### ISSUE TITLE
Version 0.36 crashes on open

### ISSUE THREAD

**Issue by DPTJKKVH** [yeriomin/YalpStore#415]
LineageOS 14.1
Xiaomi MiMix
Rooted

Installing the newest version of yalp results in an instant crash when opening the app. I first updated from 0.35 to 0.36 but later tried a clean install and also OTA versions. All result in instant crashes. Only workaround is to downgrade to 0.35.

I sent a crash report via the crash reporter.

**Comment by johanw666** [comment]
Same issue here. I sent a crash report. Could this be the reason (picked up with catlog):
```
04-10 22:58:01.024 W/System.err(13355): java.lang.RuntimeException: An error occurred while executing doInBackground()
04-10 22:58:01.025 W/System.err(13355): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
04-10 22:58:01.025 W/System.err(13355): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
04-10 22:58:01.025 W/System.err(13355): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
04-10 22:58:01.025 W/System.err(13355): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-10 22:58:01.025 W/System.err(13355): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
04-10 22:58:01.025 W/System.err(13355): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-10 22:58:01.025 W/System.err(13355): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-10 22:58:01.025 W/System.err(13355): 	at java.lang.Thread.run(Thread.java:818)
04-10 22:58:01.025 W/System.err(13355): Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set
04-10 22:58:01.025 W/System.err(13355): 	at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:234)
04-10 22:58:01.025 W/System.err(13355): 	at com.github.yeriomin.yalpstore.PreferenceUtil.getStringSet(PreferenceUtil.java:84)
04-10 22:58:01.025 W/System.err(13355): 	at com.github.yeriomin.yalpstore.BlackWhiteListManager.<init>(BlackWhiteListManager.java:35)
04-10 22:58:01.025 W/System.err(13355): 	at com.github.yeriomin.yalpstore.task.AppListValidityCheckTask.doInBackground$1059dc3f(AppListValidityCheckTask.java:105)
04-10 22:58:01.025 W/System.err(13355): 	at com.github.yeriomin.yalpstore.task.AppListValidityCheckTask.doInBackground(AppListValidityCheckTask.java:38)
04-10 22:58:01.025 W/System.err(13355): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
04-10 22:58:01.025 W/System.err(13355): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-10 22:58:01.025 W/System.err(13355): 	... 4 more
```

**Comment by yeriomin** [comment]
Release builds were crashing due to proguard misconfiguration.
https://github.com/yeriomin/YalpStore/commit/712c614b1799d72805face8eaea56bdc0c72e07f fixed this.

Tagged version 0.37 to prevent f-droid from building 0.36.
