### ISSUE TITLE
[Major issue] Yalp Store Search doesn't work

### ISSUE THREAD

**Issue by DraconicNEO** [yeriomin/YalpStore#612]
Yalp Store Can't search for apps in the search bar anymore
Also why hasn't the app been updated in over a year?

**Comment by JonnyTech** [comment]
This project is abondoned. Use Aurora Store instead: https://gitlab.com/AuroraOSS/AuroraStore

**Comment by Aldous-Huxley** [comment]
This is terrible news. In Aurora you can login with a Goolag account but you can also log in with an anonymous account just like in Yalp, which requires no Goolag account.

**Comment by johnb-xp** [comment]
I'm getting a 500 error on update checks now. Can't use Aurora Store because it's Android 5.0 and up.

**Comment by DraconicNEO** [comment]
@JonnyTech search doesn't work in Aurora either

**Comment by Booteille** [comment]
Search works in Aurora 3.0.5.
Check if you have not an older version. On F-Droid, there are two Aurora Stores: One is pre-3.0 release, the other one is the newest with Aurora rewritten from scratch!

**Comment by DraconicNEO** [comment]
@Booteille neither of the ones on F-droid work he only one that I have found that works is the latest nightly build

**Comment by Aldous-Huxley** [comment]
> @JonnyTech search doesn't work in Aurora either

Look for the Aurora Store version that is updated lately. There are two, one is abandoned and the other is the rewritten new version. Here is is: https://f-droid.org/en/packages/com.aurora.store/

**Comment by DraconicNEO** [comment]
It only works in the nightly build last time I tried search is broken in the fdroid one

**Comment by DraconicNEO** [comment]
@johnb-xp Why don't they have a Legacy version of AuroraStore for older devices?

**Comment by johnb-xp** [comment]
I've had to use MicroG Services Core and a modded APK of the Google Play Store on Android Jelly Bean. Works alright on my BlackBerry Classic and other devices. Modded Play Store is necessary because signature spoofing and rooting is impossible on BlackBerry devices. This works without root, woop woop!
https://microg.org/download.html
http://cobalt232.github.io/playstore/  (Other .apk files are unnecessary because their functions were implemented in MicroG, just install com.android.vending-6.0.0-cobalt-build2.apk)

**Comment by ghost** [comment]
It is sad since Aurora is bloated.

**Comment by tuxayo** [comment]
@pthfdr-42 
> It is sad since Aurora is bloated.

Can you elaborate?

**Comment by ghost** [comment]
It tries to be a Play Store itself and have various unnecessary features like categories etc.
I think that such applications should only do 2 things: update existing packages, and download/install packages with package names, since the user already knows what to install.

**Comment by whyorean** [comment]
@pthfdr-42 
`It tries to be a Play Store itself `
That is what exactly it is, its clearly mention in its description. "A Google Playstore Client"

`such applications`
 what you mean by such applications ?

`update existing packages, and download/install packages with package names, since the user already knows what to install` 
APKMirror or ApkUpdater is best suited for your use case maybe, but you are not everyone, don't call it bloated, please !

And whatever you consider to be a bloat is added only on public request ! Not on my own interest.

**Comment by whyorean** [comment]
@ToothlessNEO 

1. Multiple 3rd party libraries used in Aurora Store have no official support for lower version of android.
eg : Okhttp3

2. I don't own a legacy device, so its hard to develop blindly. 
    Yes, I'm aware of emulators, but my build machine specs are not enough to run emulators.

**Comment by johanw666** [comment]
AuroraStore can be compiled for minAPI19 (Kitkat), also with Okhttp downgraded to a version that still supports Kitkat. However, it crashes at startup on a Kitkat device when I do that (but the same apk runs fine on a higher Android) so there is something else going on there.

**Comment by AreYouLoco** [comment]
We have a bit of a offtopic here. What about the search engine not working?

**Comment by talk2g** [comment]
i feel the fail in my kitkat emuator, bruh.

**Comment by evermind-zz** [comment]
I forked Aurora Store and got it working on KitKat 4.4.
If anyone wants to try here is the source code
https://github.com/evermind-zz/AuroraStore

**Comment by johanw666** [comment]
Thanks @evermind-zz . I'll respond here because your repo has no option to open issues.

Building the source code works perfectly from Android Studio. When I install it on my device (Sony Z1 compact, Android 4.4.4) it starts and asks if I want Google or anonymous. I selected anonymous, and then the app crashed. I found several crashes in the logfile, who all looked like this. Seems like a UI issue to me:
```
    12-18 16:22:21.037 E/AndroidRuntime(21072): FATAL EXCEPTION: main
    12-18 16:22:21.037 E/AndroidRuntime(21072): Process: com.aurora.store.legacy, PID: 21072
    12-18 16:22:21.037 E/AndroidRuntime(21072): java.lang.VerifyError: j/c/a/q/n/m
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.c.a.c.<init>(Glide.java:43)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.c.a.c.a(Glide.java:102)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.c.a.c.a(Glide.java:14)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.c.a.c.b(Glide.java:2)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.c.a.c.c(Glide.java:1)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at h.b.k.p$i.m(AppCompatDelegateImpl.java:1)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at com.aurora.store.model.items.ClusterItem$ViewHolder.a(ClusterItem.java:11)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.h.a.b0.f.a(OnBindViewHolderListenerImpl.kt:4)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at j.h.a.b.a(FastAdapter.kt:17)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.RecyclerView$t.a(RecyclerView.java:178)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.RecyclerView$t.b(RecyclerView.java:1)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.LinearLayoutManager$c.a(LinearLayoutManager.java:9)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.GridLayoutManager.a(GridLayoutManager.java:102)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.LinearLayoutManager.a(LinearLayoutManager.java:117)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.LinearLayoutManager.c(LinearLayoutManager.java:127)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.GridLayoutManager.c(GridLayoutManager.java:25)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.RecyclerView.f(RecyclerView.java:8)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:12)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.core.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:5)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.core.widget.NestedScrollView.onMeasure(NestedScrollView.java:1)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.a(CoordinatorLayout.java:65)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:53)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:44)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:21)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.View.measure(View.java:16628)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
    12-18 16:22:21.037 E/AndroidRuntime(21072): 	at android.widget.LinearLayout.onMea
```

**Comment by evermind-zz** [comment]
@johanw666 
Thanks for reporting. I'll look into it. BTW. I've enabled issue tracking now.

**Comment by evermind-zz** [comment]
@johanw666
**edit: forget about. I could reproduce in a release build. It is related to the the proguard rules for Glide**
