### ISSUE TITLE
FC when entering in the app details 

### ISSUE THREAD

**Issue by RSDamasceno** [yeriomin/YalpStore#84]
android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:682)
at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
at android.app.ContextImpl.startActivity(<Xposed>)
at android.app.ContextImpl.startActivity(ContextImpl.java:669)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:337)
at com.github.yeriomin.yalpstore.DetailsActivity.start(DetailsActivity.java:37)
at com.github.yeriomin.yalpstore.AppListActivity$1.onItemClick(AppListActivity.java:44)
at android.widget.AdapterView.performItemClick(AdapterView.java:310)
at android.widget.AbsListView.performItemClick(AbsListView.java:1169)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3217)
at android.widget.AbsListView$4.run(AbsListView.java:4062)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5471)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

YALP.VERSION = 0.10
Build.FINGERPRINT = motorola/quark_retbr/quark_umts:6.0.1/MPGS24.107-70.2-2/2:user/release-keys
Build.HARDWARE = qcom
Build.BRAND = motorola
Build.RADIO = unknown
Build.BOOTLOADER = 0x7089
Build.DEVICE = quark_umts
Build.VERSION.SDK_INT = 23
Build.MODEL = Moto MAXX
Build.MANUFACTURER = motorola
Build.PRODUCT = cm_quark
TouchScreen = 3
Keyboard = 1
Navigation = 1
ScreenLayout = 3
HasHardKeyboard = false
HasFiveWayNavigation = false
Screen.Density = 400
Screen.Width = 1440
Screen.Height = 2560
Platforms = armeabi-v7a,armeabi
SharedLibraries = android.dolby,org.cyanogenmod.platform,com.motorola.gallery,com.qualcomm.qcnvitems,com.motorola.device,com.google.widevine.software.drm,com.google.android.media.effects,com.android.location.provider,com.arkamys.audiofx,com.quicinc.cneapiclient,com.motorola.frameworks.core.addon,com.android.future.usb.accessory,javax.obex,com.google.android.gms,org.cyanogenmod.hardware,com.huawei.audioalgo,com.motorola.android.settings.shared,org.simalliance.openmobileapi,com.qualcomm.qcrilhook,android.test.runner,com.motorola.camerabgproc,com.motorola.commandcenter.library,com.google.android.dialer.support,com.google.android.maps,com.motorola.motosignature,org.apache.http.legacy,com.android.nfc_extras,com.android.media.remotedisplay,com.quicinc.cne,com.motorola.ims.rcsmanager,com.android.mediadrm.signer,com.motorola.android.encryption
Features = android.dolby,org.cyanogenmod.platform,com.motorola.gallery,com.qualcomm.qcnvitems,com.motorola.device,com.google.widevine.software.drm,com.google.android.media.effects,com.android.location.provider,com.arkamys.audiofx,com.quicinc.cneapiclient,com.motorola.frameworks.core.addon,com.android.future.usb.accessory,javax.obex,com.google.android.gms,org.cyanogenmod.hardware,com.huawei.audioalgo,com.motorola.android.settings.shared,org.simalliance.openmobileapi,com.qualcomm.qcrilhook,android.test.runner,com.motorola.camerabgproc,com.motorola.commandcenter.library,com.google.android.dialer.support,com.google.android.maps,com.motorola.motosignature,org.apache.http.legacy,com.android.nfc_extras,com.android.media.remotedisplay,com.quicinc.cne,com.motorola.ims.rcsmanager,com.android.mediadrm.signer,com.motorola.android.encryption
Locales = af,af_NA,af_ZA,agq,ak,ak_GH,am,am_ET,ar,ar_AE,ar_BH,ar_DJ,ar_DZ,ar_EG,ar_EH,ar_ER,ar_IL,ar_IQ,ar_JO,ar_KM,ar_KW,ar_LB,ar_LY,ar_MA,ar_MR,ar_OM,ar_PS,ar_QA,ar_SA,ar_SD,ar_SO,ar_SS,ar_SY,ar_TD,ar_TN,ar_YE,as,as_IN,asa,ast,az,bas,be,be_BY,bem,bez,bg,bg_BG,bm,bn,bn_BD,bn_IN,bo,bo_CN,bo_IN,br,br_FR,brx,bs,ca,ca_AD,ca_ES,ca_FR,ca_IT,cgg,chr,cs,cs_CZ,cy,cy_GB,da,da_DK,da_GL,dav,de,de_AT,de_BE,de_CH,de_DE,de_LI,de_LU,dje,dsb,dua,dyo,dz,dz_BT,ebu,ee,ee_GH,ee_TG,el,el_CY,el_GR,en,en_AG,en_AI,en_AS,en_AU,en_BB,en_BE,en_BM,en_BS,en_BW,en_BZ,en_CA,en_CC,en_CK,en_CM,en_CX,en_DG,en_DM,en_ER,en_FJ,en_FK,en_FM,en_GB,en_GD,en_GG,en_GH,en_GI,en_GM,en_GU,en_GY,en_HK,en_IE,en_IM,en_IN,en_IO,en_JE,en_JM,en_KE,en_KI,en_KN,en_KY,en_LC,en_LR,en_LS,en_MG,en_MH,en_MO,en_MP,en_MS,en_MT,en_MU,en_MW,en_MY,en_NA,en_NF,en_NG,en_NR,en_NU,en_NZ,en_PG,en_PH,en_PK,en_PN,en_PR,en_PW,en_RW,en_SB,en_SC,en_SD,en_SG,en_SH,en_SL,en_SS,en_SX,en_SZ,en_TC,en_TK,en_TO,en_TT,en_TV,en_TZ,en_UG,en_UM,en_US,en_VC,en_VG,en_VI,en_VU,en_WS,en_ZA,en_ZM,en_ZW,eo,es,es_AR,es_BO,es_CL,es_CO,es_CR,es_CU,es_DO,es_EA,es_EC,es_ES,es_GQ,es_GT,es_HN,es_IC,es_MX,es_NI,es_PA,es_PE,es_PH,es_PR,es_PY,es_SV,es_US,es_UY,es_VE,et,et_EE,eu,eu_ES,ewo,fa,fa_AF,fa_IR,ff,ff_CM,ff_GN,ff_MR,ff_SN,fi,fi_FI,fil,fo,fo_FO,fr,fr_BE,fr_BF,fr_BI,fr_BJ,fr_BL,fr_CA,fr_CD,fr_CF,fr_CG,fr_CH,fr_CI,fr_CM,fr_DJ,fr_DZ,fr_FR,fr_GA,fr_GF,fr_GN,fr_GP,fr_GQ,fr_HT,fr_KM,fr_LU,fr_MA,fr_MC,fr_MF,fr_MG,fr_ML,fr_MQ,fr_MR,fr_MU,fr_NC,fr_NE,fr_PF,fr_PM,fr_RE,fr_RW,fr_SC,fr_SN,fr_SY,fr_TD,fr_TG,fr_TN,fr_VU,fr_WF,fr_YT,fur,fy,fy_NL,ga,ga_IE,gd,gd_GB,gl,gl_ES,gsw,gu,gu_IN,guz,gv,gv_IM,ha,haw,iw,iw_IL,hi,hi_IN,hr,hr_BA,hr_HR,hsb,hu,hu_HU,hy,hy_AM,in,in_ID,ig,ig_NG,ii,ii_CN,is,is_IS,it,it_CH,it_IT,it_SM,ja,ja_JP,jgo,jmc,ka,ka_GE,kab,kam,kde,kea,khq,ki,ki_KE,kk,kkj,kl,kl_GL,kln,km,km_KH,kn,kn_IN,ko,ko_KP,ko_KR,kok,ks,ksb,ksf,ksh,kw,kw_GB,ky,lag,lb,lb_LU,lg,lg_UG,lkt,ln,ln_AO,ln_CD,ln_CF,ln_CG,lo,lo_LA,lt,lt_LT,lu,lu_CD,luo,luy,lv,lv_LV,mas,mer,mfe,mg,mg_MG,mgh,mgo,mk,mk_MK,ml,ml_IN,mn,mr,mr_IN,ms,mt,mt_MT,mua,my,my_MM,naq,nb,nb_NO,nb_SJ,nd,nd_ZW,ne,ne_IN,ne_NP,nl,nl_AW,nl_BE,nl_BQ,nl_CW,nl_NL,nl_SR,nl_SX,nmg,nn,nn_NO,nnh,nus,nyn,om,om_ET,om_KE,or,or_IN,os,os_GE,os_RU,pa,pl,pl_PL,ps,ps_AF,pt,pt_AO,pt_BR,pt_CV,pt_GW,pt_MO,pt_MZ,pt_PT,pt_ST,pt_TL,qu,qu_BO,qu_EC,qu_PE,rm,rm_CH,rn,rn_BI,ro,ro_MD,ro_RO,rof,ru,ru_BY,ru_KG,ru_KZ,ru_MD,ru_RU,ru_UA,rw,rw_RW,rwk,sah,saq,sbp,se,se_FI,se_NO,se_SE,seh,ses,sg,sg_CF,shi,si,si_LK,sk,sk_SK,sl,sl_SI,smn,sn,sn_ZW,so,so_DJ,so_ET,so_KE,so_SO,sq,sq_AL,sq_MK,sq_XK,sr,sv,sv_AX,sv_FI,sv_SE,sw,sw_CD,sw_KE,sw_TZ,sw_UG,ta,ta_IN,ta_LK,ta_MY,ta_SG,te,te_IN,teo,th,th_TH,ti,ti_ER,ti_ET,to,to_TO,tr,tr_CY,tr_TR,twq,tzm,ug,uk,uk_UA,ur,ur_IN,ur_PK,uz,vai,vi,vi_VN,vun,wae,xog,yav,ji,yo,yo_BJ,yo_NG,zgh,zh,zu,zu_ZA

**Comment by RSDamasceno** [comment]
Thanks for the fix!
